# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        node-version: [14.x]
        
    runs-on: ${{ matrix.os }}

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - run: npx dependents --package mineflayer --sort downloads
    - run: npm install
    - run: npm run build --if-present
    - run: npm test
    - run: echo ${{ github.event }}
    - name: Upload artifact
      uses: actions/upload-artifact@v2
      with:
        name: dist-${{ matrix.os }}
        path: |
          *.dat
#   debug:
#     runs-on: ubuntu-latest
#     steps:
#     - name: Debug Action
#       uses: hmarr/debug-action@v1.0.0
  release:
    needs: build
    runs-on: ubuntu-latest
    if: startsWith(github.ref, 'refs/tags')
    steps:
      - name: Download artefacts
        uses: actions/download-artifact@v2
        with:
          path: dists
      - name: Display structure of downloaded files
        run: ls -R
          

