name: Test workflow
on: [workflow_dispatch]

jobs:
  example:
    name: Example Job
    runs-on: ubuntu-latest
    steps:
      - name: Clone Repository
        uses: actions/checkout@v2
      - name: Say hello
        run: echo "Hello world"
      #- run: sudo apt-get install llvm-dev
      - run: sudo add-apt-repository "deb http://archive.ubuntu.com/ubuntu focal universe"
      - run: sudo apt-get update
      - run: cat /etc/apt/sources.list
      - run: sudo snap install radare2 --channel=edge --classic
      - run: ls /snap/bin/r* && which radare2
      - run: radare2
      - run: /snap/bin/radare2.rabin2 -N 1 -z /snap/bin/radare2.rabin2
      - run: llvm-config-14 --cxxflags --ldflags --libs
      - run: clang --version
      - run: which clang
      - run: cat /usr/lib/llvm-14/include/llvm/Demangle/Demangle.h

