name: Test workflow
on: [workflow_dispatch]

jobs:
  example:
    name: Example Job
    runs-on: ubuntu-latest
    steps:
      - name: Clone Repository
        uses: actions/checkout@v2
      - name: Say hello
        run: echo "Hello world"
      - name: Install LLVM and Clang
        uses: KyleMayes/install-llvm-action@v1
        with:
          version: "18.0"
      - run: clang --version
      - run: which clang
      - run: ls /usr/lib/llvm/


