name: Test workflow
on: [workflow_dispatch]

jobs:
  example:
    name: Example Job
    runs-on: ubuntu-latest
    steps:
      - name: Clone Repository
        uses: actions/checkout@v2
      - name: Say hello
        run: echo "Hello world"
      #- run: sudo apt-get install llvm-dev
      - run: sudo apt-get install libradare2-dev
      - run: wget -O r2.deb http://archive.ubuntu.com/ubuntu/pool/universe/r/radare2/radare2_4.2.1+dfsg-2_amd64.deb
      - run: sudo dpkg -i r2.deb && sudo apt-get install -f
      - run: llvm-config-14 --cxxflags --ldflags --libs
      - run: clang --version
      - run: which clang
      - run: cat /usr/lib/llvm-14/include/llvm/Demangle/Demangle.h

