name: Test workflow
on: [workflow_dispatch]

jobs:
  example:
    name: Example Job
    runs-on: ubuntu-latest
    steps:
      - name: Clone Repository
        uses: actions/checkout@v2
      - name: Say hello
        run: echo "Hello world"
      - run: clang --version
      - run: which clang
